<?php

// catch post requests
if (!empty($_POST['action']) && $_POST['action'] == 'knspost') {
	zh_wc_widget_ajax()->kns_construct_cart("ids");
}

defined( 'ABSPATH' ) or exit;
add_action( 'plugins_loaded', 'zh_wc_widget_ajax' );

class ZH_WC_Widget_Ajax {
	protected static $instance;
	public static function instance() {
		if ( is_null( self::$instance ) ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	public function __construct() {
	}

	// FIXME: Woocommerce global == null
	// TODO: implement Ajax
	function remove_cart_item($cart_item_key) {
		global $woocommerce;
		// needs to be cart item key
		// $cart = $woocommerce->cart->get_cart();
		// echo $cart;
		var_dump($woocommerce);
		$woocommerce->cart->remove_cart_item($cart_item_key);
		echo $cart_item_key;

		exit;
	}

	function kns_construct_cart($products) {
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "https://www.keynoteseries.com/course_details/KEYNOTESERIESOnline/Beneath%20the%20Surface:%20Understanding%20the%20Anatomy%20of%20a%20House?");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		$post_fields = [
			'cart_add'           => 1,
			'CRSCredit'          => 1,
			'AdditionalOrg[194]' => 28
		];
		curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($post_fields));
		curl_setopt($ch, CURLOPT_POST, 1);

		$headers = array();
		session_start();
		// REVIEW: cannot be implemented wo stealing phpsessid from keynoteseries
		$cookie_phpsessid = "Cookie: PHPSESSID=" . session_id($sid);
		var_dump($cookie_phpsessid);
		var_dump($_COOKIE['phpsessid']);
		$headers[] = $cookie_phpsessid;

		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$response = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		var_dump($response);
		curl_close ($ch);

		// $post = [
	  //   'cart_update'           => 1,
	  //   'removeCartItem%5B%5D' => 2340
		// ];
	}



}

/**
 * Returns the One True Instance of WC Widget.
 *
 * @return ZH_WC_Widget
 */
function zh_wc_widget_ajax() {
	return ZH_WC_Widget_Ajax::instance();
}

zh_wc_widget_ajax();
